### ISSUE TITLE
Spikes appear on the Network Analyzer plot

### ISSUE THREAD

**Issue by amiclaus** [analogdevicesinc/scopy#167]
Scopy version: 4b0a59a, OS: Windows 7, Firmware: v0.14

Connect a simple RC HPF (Fc ~ 340Hz) to the Network Analyzer.
Make a sweep between 100Hz-10MHz.

Random spikes appear on the plot (maybe repeat the sweep several times to get the spikes).
![spikes](https://user-images.githubusercontent.com/26061529/28019295-263e6bd0-6589-11e7-820e-7fd5dfd4c60d.PNG)

**Comment by pcercuei** [comment]
Could you move the "sweep gets stuck" thing in its own bug report?

**Comment by amiclaus** [comment]
Sure

**Comment by pcercuei** [comment]
The spikes appear when the buffer size of the ADC does not contain an integer number of periods. There is already a mechanism in place for the DAC to ensure that the buffer will contain an integer number of periods, it should be adapted for the ADC path as well.

**Comment by rgetz** [comment]
When performing an FFT on data, use a window function - it will make sure that it doesn't matter if you have an exact number of periods.

**Comment by damercer** [comment]
To Robin's suggestion of using a window function for the FFT. If you don't go with picking frequencies that fall in the center of an FFT bin you will need to use a flat-top FFT window to get accurate amplitude and phase results. Not all window function are created equal.

**Comment by rgetz** [comment]
Yes; I should have been more specific. Math/equation at:

https://en.m.wikipedia.org/wiki/Window_function#Flat_top_window

**Comment by damercer** [comment]
There is Python code that calculates a flat-top window ( and others ) in 
ALICE if that is any help.

Doug

**Comment by pcercuei** [comment]
So we actually don't use a FFT there, we just cross-correlate with a cosine.

**Comment by rgetz** [comment]
Most cross correlations use an FFT, a cross product, and an IFFT. A window function can still be used. 

What's the algorithm for your xcorr?

**Comment by pcercuei** [comment]
No idea :)
I just use the complex multiply block from GNU Radio.

**Comment by rgetz** [comment]
To do a proper cross correlation, you can't use a simple multiply. 

Try something like:
http://www.olifantasia.com/projects/gnuradio/mdvh/passive_radar/correlator.py

**Comment by pcercuei** [comment]
Well, I guess I don't cross-correlate, then.
This is more or less the flowgraph that Scopy generates:

![flowgraph](https://user-images.githubusercontent.com/403272/28070033-e233c5b6-664b-11e7-8e5b-72c04b707d8f.png)

**Comment by damercer** [comment]
Not to get too deep in the weeds on this but it would seem to me that just doing an FFT and getting the amplitude and phase ( difference between input and output ) would be simpler.
You already know what frequency the peak should be at but you can easily search the array to
find it. I'm assuming that in the Spectrum Analyzer you are doing FFTs and you should just reuse that stuff while sweeping the sine source.

Doug

**Comment by lclausen-adi** [comment]
The current code essentially does a FFT for a single bin. But it is more precise since we can choose the center frequency of the bin freely to match the frequency of the sweep tone.

**Comment by rgetz** [comment]
Hate to say it - but if it was more precise - we wouldn't be seeing the spikes/errors in the data :)

I have seen lots worse than the above when looking at things.

I think it is independent FFT on both signals, (assuming you have 10-100 periods or more of the waveform) find the peaks in both FFTs, and take a ratio of amplitudes, and a simple subtraction for phase difference. That may be more computationally complex, but should eliminate the errors (be less sensitive to full periods on buffer boundaries)

**Comment by damercer** [comment]
That is exactly what I was thinking to myself. Robin was brave enough to 
actually say it out loud.

Doug

**Comment by lclausen-adi** [comment]
The spikes are most likely an artifact of implementation not the algorithm. Changing the algorithm wont necessarily fix that.

**Comment by pcercuei** [comment]
Changing the whole algorithm right now would make no sense, I'm not doing that. Again, we can fix this bug by just making sure that the buffer size of the ADC is properly calculated.

**Comment by amiclaus** [comment]
On Scopy build: 3aae9de (v0.6) the bug is fixed.

**Comment by amiclaus** [comment]
Scopy version: 9bf9997
It seems that the issue persists: RC LPF with Fc ~ 150Hz.
![capture](https://user-images.githubusercontent.com/26061529/29364897-b220750e-829d-11e7-8e0b-d5244dee9114.PNG)

For a HPF the spikes are less pronounced:
![capture1](https://user-images.githubusercontent.com/26061529/29365219-dc554268-829e-11e7-8b55-97b6143b388c.PNG)

**Comment by damercer** [comment]
It looks like the bad data is happening mostly in places where the input signal level is small, -30 to -50dB. Which analog input gain range is it in when taking measurements? The high noise floor of the low gain range could be causing issues. I've noticed some of the same issues in my software as well, much worse in low gain mode but still happens a little in high gain mode when input signal level is very small.

The M2K just does not have the dynamic range of Analog Discovery or M1K.

Doug

**Comment by pcercuei** [comment]
I think this is a different problem, and not a software one. Proof, increasing the amplitude of the waveform decreases the jitter.

**Comment by adisuciu** [comment]
This issue seems to be solved in the lastest version of Scopy.
However there seems to be some jitter toward the far end of the frequency, which I guess makes sense. Given the fact that our sampling freq is 75MHz, we can't accurately measure the amplitude of a 23MHz signal (for example), especially if that signal has a low amplitude. My suggestion would be to limit the sweep range to 10MHz.
![scopy_2018-01-23_11-22-31](https://user-images.githubusercontent.com/8676912/35269489-d6091e2a-0034-11e8-9241-9dc880338bfb.png)
![scopy_2018-01-23_11-53-19](https://user-images.githubusercontent.com/8676912/35269491-d64442d4-0034-11e8-81ab-1152c0af5522.png)

**Comment by amiclaus** [comment]
This issue is solved on Scopy v0.10 release.
